server:
    port: 8080
#    ssl:
#        key-store: keystore.p12
#        key-store-password: 123456
#        keyStoreType: PKCS12
#        server.ssl.keyAlias: tomcat
spring:
    application:
        name: smallprogram
    profiles:
        active: dev
    datasource:
        name: nn
        url: jdbc:mysql://localhost:3306/nn?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT&&zeroDateTimeBehavior=convertToNull
        username: root
        password: admin
        #druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver

        druid:
            #druid监控
            web-stat-filter:
                profile-enable: true
                #exclusions: *.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*
            stat-view-servlet:
                allow: 172.16.2.119,172.16.2.129
                deny:
                login-username: admin
                login-password: 123456
                url-pattern: /druid/*
            filters: stat,wall,log4j
            initial-size: 5
            min-idle: 5
            maxActive: 20
            max-wait: 60000
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            validation-query: select 1 from dual
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            connection-properties:
            #connectionProperties: druid.stat.mergeSql: true;druid.stat.slowSqlMillis: 5000
    jmx:
        enabled: false
#mybatis配置
mybatis:
    mapper-locations: classpath:mapping/*.xml
    type-aliases-package: com.nainai.smallprogram.domain
    configuration:
        call-setters-on-nulls: true
logging:
    level:
        com:
          nainai:
            smallprogram:
              mapper: debug




